# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d3e36e9d3448e9a7243490c978a0cc24d60d9507dea036aa8f304a9005a4b7396c89b75a719927af0a7068b9deb07634549fd8aca9f3ff6ac7d6f27b33f23b
  google_oauth_client_id: 68497528850-e1voe2mm5cr81qs88oia8lpvappbg0r0.apps.googleusercontent.com
  google_oauth_project_id: dnd-companion-154713
  google_oauth_client_secret: ijHHn2GY8_UdHLlO9Xd9M33X
  google_oauth_auth_uri: https://accounts.google.com/o/oauth2/auth
  google_oauth_token_uri: https://accounts.google.com/o/oauth2/token
  google_oauth_auth_provider_x509_cert_uri: https://www.googleapis.com/oauth2/v1/certs

test:
  secret_key_base: 03e1f9c79f1d38de2be3023cd0935b09d7983a6b9a85a67e0dfc17ca3dcf1685fb8f606fcb7148b8b77aabdfbca68767a0f217118f89311452c9f77d0561cc92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
